### ISSUE TITLE
how to use htk_io for reading a .htk file?

### ISSUE THREAD

**Issue by vincentvanhees** [MattShannon/htk_io#1]
I am trying to read a .htk file with htk_io and I am not sure where to start.

The README says "Examples of usage of various functions and classes are included in their docstrings.", but I am struggling to navigate the docstrings as none of the files or inside functions has a name that hints at a file reading or loading functionality. What I also find confusing is the .lab files in the example folder, I thought the library is meant to read .htk files and not .lab files?

Any guidance will be much appreciated

**Comment by MattShannon** [comment]
Hi Vincent, I'm afraid reading HTK format parameter files (https://labrosa.ee.columbia.edu/doc/HTKBook21/node58.html) is not supported. I was mainly using HTS for storing parameter files when I wrote this, so I only implemented that.

I believe the HTK parameter file format is just a fixed size header followed by a sequence of samples (e.g. see the link above). So you could try modifying the code in vecseq.py (which reads HTS parameter files which are headerless) to strip the fixed size header. There's an example in the HTS demo in data/scripts/addhtkheader.pl of doing the opposite to what you want (adding a header rather than removing it). It also looks like HTK's HCopy command could be used with TARGETKIND NOHEAD to strip the header from the output files, at which point you should be able to read it using vecseq.py. Hope that helps!
